"""Initial migration

Revision ID: c88468b7ab0b
Revises:
Create Date: 2025-10-26 20:56:50.285200

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88468b7ab0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_packet_import_time', table_name='packet')
    op.create_index('idx_packet_import_time', 'packet', [sa.text('import_time DESC')], unique=False)
    op.create_index('idx_packet_seen_packet_id', 'packet_seen', ['packet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_packet_seen_packet_id', table_name='packet_seen')
    op.drop_index('idx_packet_import_time', table_name='packet')
    op.create_index('idx_packet_import_time', 'packet', ['import_time'], unique=False)
    # ### end Alembic commands ###
